(part "PT-2040PQ"
    (packageRef "PT2040PQ")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "539-PT2040PQ")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mallory-Sonalert/PT-2040PQ?qs=l%2Fkuw%2F8%252BD9j2AVf7eGaf%252BA%3D%3D")
    (property "Manufacturer_Name" "Mallory Sonalert")
    (property "Manufacturer_Part_Number" "PT-2040PQ")
    (property "Description" "Audio Indicators & Alerts XDUCR, PIEZO, 4KHZ 90DB, PC PINS, 22X9")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/SFDatasheet-1/sf-00027599.pdf")
    (property "symbolName1" "PT-2040PQ")
)
