(part "SMF5_0A-T13"
    (packageRef "SODFL3618X110N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "576-SMF5.0A-T13")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Littelfuse/SMF5.0A-T13?qs=aGgfWYEhH7lEohru0mAWAg%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "SMF5.0A-T13")
    (property "Description" "LITTELFUSE - SMF5.0A-T13 - TVS Diode, SMF Series, Unidirectional, 5 V, 9.2 V, SOD-123FL, 2 Pins")
    (property "Datasheet_Link" "https://www.littelfuse.com/~/media/electronics/datasheets/tvs_diodes/littelfuse_tvs_diode_smf_datasheet.pdf.pdf")
    (property "symbolName1" "SMF5_0A-T13")
)
