(part "D6R60_F1_LFS"
    (packageRef "D6R60F1LFS")
    (interface
        (port "1" (symbPinId 1) (portName "COM_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NO_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "611-D6R60F1LFS")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/CK/D6R60-F1-LFS?qs=ljbEvF4DwON75ZvAORmL0g%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "D6R60 F1 LFS")
    (property "Description" "Switch: keypad; Pos:2; SPST-NO; 0.01A/32VDC; blue; THT; 1.3N; round")
    (property "Datasheet_Link" "")
    (property "symbolName1" "D6R60_F1_LFS")
)
